name: RedStonePvP
main: me.redpvp.Main.Main
version: 1.0
author: O16
commands:
  ranks:
  trash:
  stats:
  build:
  invsee:
  v:
  discord:
  website:
  store:
  help:
  ping:
  gmc:
  gms: