name: RedStonePvP
main: Main.Main
version: 3.0
author: O16
description: RedStonePvP version 3.0 developed by O16!
commands:
  ranks:
  trash:
  iixxxWARPSxxxii:
  iixxxMINERxxxii:
  iixxxSHOPxxxii: